import { chromium } from 'playwright';
const out = process.argv[2];
const b = await chromium.launch(); const p = await b.newPage({viewport:{width:1440,height:900}});
await p.goto('https://jtlgrowth.com/workshop/?live=' + Date.now(), {waitUntil:'networkidle'});
await p.evaluate(async()=>{for(let y=0;y<document.body.scrollHeight;y+=500){window.scrollTo(0,y);await new Promise(r=>setTimeout(r,120));} window.scrollTo(0,0);});
await p.waitForTimeout(1500);
const info = await p.evaluate(()=>({figs:document.querySelectorAll('figure.wk-photo').length, broken:[...document.images].filter(i=>i.naturalWidth===0).length, video:!!document.querySelector('#room video'), title:document.title}));
await p.screenshot({path: out + '/workshop-recap-live-2026-09-03.png', fullPage:true});
await p.screenshot({path: 'live-recap-top.png'});
console.log('LIVE_SHOT', JSON.stringify(info)); await b.close();
